### ISSUE TITLE
FATAL undefined is not a function

### ISSUE THREAD

**Issue by pozitron57** [alexbruno/hexo-generator-json-content#11]
Hi, I have this plugin working just fine on one computer, but on the second computer I have the following error when I try to generate site with `hexo s`  

```
➜  hexo hexo s
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: undefined is not a function
    at /home/slisakov/hexo/node_modules/hexo-generator-json-content/index.js:78:20
    at Query.filter (/home/slisakov/hexo/node_modules/warehouse/lib/query.js:305:9)
    at Hexo.hexo_generator_json_content (/home/slisakov/hexo/node_modules/hexo-generator-json-content/index.js:76:30)
    at Hexo.tryCatcher (/home/slisakov/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/slisakov/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/slisakov/hexo/node_modules/hexo/lib/hexo/index.js:337:24
    at tryCatcher (/home/slisakov/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/slisakov/hexo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/slisakov/hexo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init [as _init$] (/home/slisakov/hexo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (/home/slisakov/hexo/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/slisakov/hexo/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/slisakov/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/slisakov/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
FATAL undefined is not a function
TypeError: undefined is not a function
    at /home/slisakov/hexo/node_modules/hexo-generator-json-content/index.js:78:20
    at Query.filter (/home/slisakov/hexo/node_modules/warehouse/lib/query.js:305:9)
    at Hexo.hexo_generator_json_content (/home/slisakov/hexo/node_modules/hexo-generator-json-content/index.js:76:30)
    at Hexo.tryCatcher (/home/slisakov/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/slisakov/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/slisakov/hexo/node_modules/hexo/lib/hexo/index.js:337:24
    at tryCatcher (/home/slisakov/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/slisakov/hexo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/slisakov/hexo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init [as _init$] (/home/slisakov/hexo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (/home/slisakov/hexo/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/slisakov/hexo/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/slisakov/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/slisakov/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Please let me know if you have a guess why it is happening. Also I have tried other hexo json generators, but all of them are not working on this computer.

**Comment by alexbruno** [comment]
Hi, sorry for late response!

I will try to debug this and return soon.

**Comment by alexbruno** [comment]
Hey @pozitron57 did you solved it?
What was the problem?

**Comment by pozitron57** [comment]
@alexbruno, no, I did not solve it. Actually, I didn't try to solve it, it became unnecessary. Node.js version is 0.12.17. As I told, on other computers everything is working fine for me as well.

**Comment by alexbruno** [comment]
Oh, right!
This plugin was coded with ES6, you need latest version of Node.js to use it.
But, why you are using that very old and deprecated version of node???
Latest LTS version is 6.9.2 !!!

[Node.js](https://nodejs.org/en/)

**Comment by pozitron57** [comment]
I updated Node.js and now everything works fine, thanks! I have no idea why I had such an old version of node...

**Comment by alexbruno** [comment]
You're welcome!
