### ISSUE TITLE
Plugin failing to load

### ISSUE THREAD

**Issue by JohnBlood** [alexbruno/hexo-generator-json-content#13]
I installed the plugin using the instructions. When I tried to serve the site, I got this error. Any ideas?

```
$ hexo server
ERROR Plugin load failed: hexo-generator-json-content
SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup               ported outside strict mode
    at Object.exports.runInThisContext (vm.js:53:16)
    at C:\hexo\manjaro-rocks\node_modules\hexo\lib\hexo\index.js:227:17
    at tryCatcher (C:\hexo\manjaro-rocks\node_modules\hexo\node_modules\bluebird               \js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\hexo\manjaro-rocks\node_modules\hex               o\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\hexo\manjaro-rocks\node_modules\hexo\node_modu               les\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\hexo\manjaro-rocks\node_modules\hexo\node_mod               ules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\hexo\manjaro-rocks\node_modules\hexo\node_mod               ules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\hexo\manjaro-rocks\node_modules\hexo\node_modules\bl               uebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\hexo\manjaro-rocks\node_modules\hexo\node_mo               dules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (C:\hexo\manjaro-rocks\node_modules\hex               o\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (C:\hexo\manjaro-rocks\node_modules\hexo\node_modu               les\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\hexo\manjaro-rocks\node_modules\hexo\node_mod               ules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\hexo\manjaro-rocks\node_modules\hexo\node_mod               ules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\hexo\manjaro-rocks\node_modules\hexo\node_modules\bl               uebird\js\release\promise.js:636:18)
    at C:\hexo\manjaro-rocks\node_modules\hexo\node_modules\bluebird\js\release\               nodeback.js:42:21
    at C:\hexo\manjaro-rocks\node_modules\hexo\node_modules\hexo-fs\node_modules               \graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
FATAL Port 4000 has been used. Try other port instead.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/do               cs/troubleshooting.html
Error: listen EADDRINUSE 0.0.0.0:4000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
FATAL listen EADDRINUSE 0.0.0.0:4000
Error: listen EADDRINUSE 0.0.0.0:4000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
```

**Comment by alexbruno** [comment]
Sorry for late response!
Did you already fix it?
You can see the problem at line started with "SyntaxError".
Latest version was coded with ES6 syntax. You need latest version of Node.js to compile it correctly.

**Comment by JohnBlood** [comment]
After you contacted me, I checked what versions I had of nodejs and npm. npm was at version 2.14.20 and node was 4.4.0. I updated both and now have npm 4.0.5 and node 6.9.1. I haven't had a chance to see if it fixed the problem. Will reply when I try it.

**Comment by alexbruno** [comment]
Ok, I'll wait for your feedback.

**Comment by FateZeros** [comment]
Hi, when I npm install -S  hexo-generator-json-content 
![image](https://cloud.githubusercontent.com/assets/18113191/21035031/2d30e542-bdf7-11e6-8c1b-dcc4a5907063.png)
And then I hexo s ,I got en error like @JohnBlood ,How can I solve this?

**Comment by alexbruno** [comment]
Ok, I'm waiting for your feedback.

**Comment by JohnBlood** [comment]
@alexbruno I finally got a chance to try it. I reinstalled the plugin and ran `hexo server`. I didn't get an error and the search works nicely. Thanks for the advice.
