### ISSUE TITLE
ERROR Plugin load failed when hexo clean

### ISSUE THREAD

**Issue by kingkillua** [alexbruno/hexo-generator-json-content#18]
**befor that,when i installed  it
everything allright but a warm:**
[root@killua blog]# npm i -S hexo-generator-json-content
npm WARN engine keyword-extractor@0.0.13: wanted: {"node":"node >= 0.10.0"} (current: {"node":"0.12.4","npm":"2.10.1"})

**error info when hexo clean:**
`[root@killua blog]# hexo clean
ERROR Plugin load failed: hexo-generator-json-content
/home/killua/blog/node_modules/hexo-generator-json-content/index.js:4
	minify = str => util.stripHTML(str).trim().replace(/\n/g, ' ').replace(/\s+/g
	             ^^
SyntaxError: Unexpected token =>
    at Object.exports.runInThisContext (vm.js:73:16)
    at /home/killua/blog/node_modules/hexo/lib/hexo/index.js:227:17
    at tryCatcher (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at /home/killua/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/killua/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:334:14
    at /home/killua/blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/killua/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/killua/blog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/killua/.nvm/versions/node/v0.12.4/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:95:15)
INFO  Deleted database.
`

**Comment by adamzhoul** [comment]
node go version5.8 ; hexo-generator-json-content version 2.x

**Comment by alexbruno** [comment]
Hello, sorry for late response!

@adamzhoul is right, you are using a very, very old Node version.
